### ISSUE TITLE
Class Illuminate\Events\CallQueuedHandler does not exist 

### ISSUE THREAD

**Issue by liurenqiu520** [snower/forsun-laravel#8]
Class Illuminate\Events\CallQueuedHandler does not exist 
Laravel 5.6.29

**Comment by liurenqiu520** [comment]
?

**Comment by snower** [comment]
https://github.com/snower/forsun-laravel/blob/master/src/Builder.php#L216

参照Laravel队列在这个地方组了一个回调请求，Laravel 5.6是不是修改了这个？Laravel 5.6不太熟。。

**Comment by liurenqiu520** [comment]
Laravel 5.6 CallQueuedHandler 移动到 Illuminate\Queue 了，而且好像也改动了一些方法。

**Comment by dishcheng** [comment]
5.5也出现了这个问题

**Comment by snower** [comment]
修复了，5.7 5.8也测试也都ok了

**Comment by dishcheng** [comment]
> 修复了，5.7 5.8也测试也都ok了

没有同步到packagist上面，packagist最新还是1.0.4，最新的拉不下来

**Comment by snower** [comment]
现在应该可以了呢，原来是github的webhook更新了

**Comment by dishcheng** [comment]
> 现在应该可以了呢，原来是github的webhook更新了

嗯，可以拉了。另外想问一下，是不是readme上面的步骤走完后，还要在supervisor里面配置queue:work？我的好想跑完后，如果不运行queue:work，redis队列会不断添加，但是没有执行，运行queue:work就都开始执行了

**Comment by snower** [comment]
肯定的啊，这个项目提供的是定时调度，真正任务的运行肯定是由laravel对列来完成的，从系统结构上来说，定时调度和队列本身也应属两个不同服务才更利于稳定和扩展性的

**Comment by dishcheng** [comment]
好的，了解了，我可能被`驱动原生Laravel Schedule运行`这句话误解了，以为那条命令运行后不需要用queue:work了，非常感谢
.ps:项目很不错。以后有机会会用在项目里面，已star

**Comment by snower** [comment]
驱动原生Laravel Schedule运行 这个嘛，是这样的，Laravel的Schedule能运行是需要crontab的，但是如果你部署多台服务器的话，只在其中一台部署crontab会有负载单点，每台都部署吧又会重复执行相同任务，所以可以在forsun中注册，通过forsun来触发原生定时任务的运行，当然这个仍然由队列来执行的
